INSERT INTO TB_WORKER(NAME, DAILY_INCOME) VALUES ('Jackson Almeida', 69.0);
INSERT INTO TB_WORKER(NAME, DAILY_INCOME)  VALUES ('Elisama Melo', 100.69);
INSERT INTO TB_WORKER(NAME, DAILY_INCOME)  VALUES ('Viviane Almeida', 105.0);